### PR TITLE
Feat/assumption controls

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by freefony** [comment]
Please don't review or merge this. still work in progress

**Comment by janetbutts** [comment]
@musamusa , please review

**Comment by musamusa** [comment]
@freefony are you done with this?

**Comment by freefony** [comment]
not yet

**Comment by freefony** [comment]
@janetbutts, Am closing this branch as other branches have taken care of it's features and structures have changed since.

**Comment by janetbutts** [comment]
@freefony , then should this ticket get closed.

**Pull request closed without merging**
