### PR TITLE
Bug/configuration location validation

### LINKED ISSUE #271: Configuration>Locations: The save button shows as an inactive icon
The save function isn't working. The icon doesn't show as active and the user is unable to save the locations

### PR DESCRIPTION
**Pull request by freefony**
closes #271

### CODE REVIEW

**Comment by tlvince** [comment]
@freefony do you have an example CSV for this? I mocked one up, but couldn't get the table to display anything after upload. Also, with an empty file `touch empty.csv`, no error/warning was shown.

**Comment by janetbutts** [comment]
@freefony , please provide @tlvince with the requested file

**Comment by freefony** [comment]
shared the link to "locations" folder on google drive

**Comment by tlvince** [comment]
Still having some trouble with this.
- When I upload `kano-lgas.csv`, the table is populated, but I'm shown "file not uploaded" when I hit save
- When I upload `kano-zones.csv`, the table is partially-populated (empty OSMID, Zone and LGA columns) and save is disabled
- When I upload `bicha lgas.csv` (under LGAs and choosing Bichi from the zone drop down), the table populates (besides the LGA column), but I'm shown "file not uploaded" when I hit save

**Comment by tlvince** [comment]
Handing over to @Chima1707 (:gift:) as I'm out until 22nd.

**Comment by DonkeyOatie** [comment]
assigned to @Chima1707 for review as @musamusa is not currently working on this project

**Comment by freefony** [comment]
@tlvince , 
1. Yeah you are not supposed to upload all lgas together. the expected behavior is to upload for each zone
2 & 3 i can't reproduce these, it saves the documents

**Pull request merged**
