### PR TITLE
chore: remove imagemin

### PR DESCRIPTION
**Pull request by tlvince**
Imagmin (and its dependencies) are notoriously flakey to install (I keep running
into `gifsicle: Installing failed, pre-build test failed`).
generator-gulp-angular itself puts this feature behind an advanced flag.

Since we've only two images, pre-optimise them (with `optipng -o7 -strip all`)
and remove the gulp task.

### CODE REVIEW

**Comment by tlvince** [comment]
@jofomah can I get a hell yeah?

**Comment by tlvince** [comment]
OK, this is working with Node v0.12.7.

**Comment by jofomah** [comment]
@tlvince yes go ahead

**Comment by tlvince** [comment]
If for some reason we add a load of images, we may consider reverting this. Or otherwise, just make sure we pre-optimise them before committing.

**Pull request merged**
