### PR TITLE
feature/report delivery success failure cancelled

### LINKED ISSUE #45: capture number of success, failed and cancelled deliveries for each driver per zone
If you have any questions, ask adamu lawan

### PR DESCRIPTION
**Pull request by musamusa**
Closes #45

### CODE REVIEW

**Comment by jofomah** [comment]
@musamusa what is the status of this PR, from what am seeing it is just a copy of the PR i sent in for cumulative report?? what i mean is it just changes the same file i have sent in already

**Comment by jofomah** [comment]
@musamusa also the whole idea here is to split each workflow into its own controller, so i think Facility Status report which is what you are working on should go to Facility Status Report Controller

**Comment by musamusa** [comment]
@jofomah its complete, Yes its a copy of the cumulative report, also I had to combine both reports in same controller since they share same logic and couchdb view.

**Comment by janetbutts** [comment]
@jofomah , please review

**Pull request merged**
