### PR TITLE
Feature/angular production option

### PR DESCRIPTION
**Pull request by Chima1707**
added production options

### CODE REVIEW

**Comment by tlvince** [comment]
@Chima1707 this PR contains #355. I suspect you branched off of `Chima1707:bug/spurious-user-not-found` rather than `develop`?

**Comment by Chima1707** [comment]
Yea, that is true, i i forgot to remove it. will update it now

**Comment by tlvince** [comment]
Thanks. This still seems to be combined with the user states commits, so lets wait until that's merged before merging this (unless you can open a new PR ensuring it only contains the production options).

**Comment by Chima1707** [comment]
Ok lets wait for user states commits to be merged

**Comment by tlvince** [comment]
Since I was free, I cherry picked your changes in c9727a4 (with a slight style tweak). Thanks.

**Pull request closed without merging**
