### PR TITLE
Fix/session timeout bug

### LINKED ISSUE #15: Handle user sessions properly

### PR DESCRIPTION
**Pull request by jofomah**
Note: shows multiple alert for each db call that fails, this needs to be fixed though or might leave it like that.

fixes #15

### CODE REVIEW

**Comment by tlvince** [comment]
Nice simple approach. Haven't tested yet, but will give it a roll sometime this afternoon.

**Comment by jofomah** [comment]
decided to try this out since couchdb-auth is same as login-service, similar approach with retriables without having to extend or use those login-service and login-dialog

**Comment by tlvince** [comment]
:+1:

**Comment by tlvince** [comment]
Can reproduce the multiple alerts:

screen shot 2015-10-24 at 17 47 13

… but I think that's another issue (#154).

LGTM.

**Pull request merged**
