### PR TITLE
Feature/user state service

### LINKED ISSUE #335: Rounds aren't shown until state is chosen
If I log in as gis user (who has Kano state role), the state dropdown correctly selects Kano, but no rounds are shown on the homepage (after #257) until I reselect Kano from the dropdown.

### LINKED ISSUE #346: Navbar: refreshing page resets state selection
When logged in as a user that has access to all states information (e.g. super) and selecting a state other than the default (current default: Bauchi), refreshing the page causes the state the be reset to the default state.  This is a minor bug but is inconvenient, particularly on the reports page.

This was discovered because the "invoice" side bar nav is slow to react to a click and I refreshed the page to see if it was reacting at all.

env: dev-dd.ehealth.org.ng

### PR DESCRIPTION
**Pull request by Chima1707**
closes #335  closes #346

### CODE REVIEW

**Comment by freefony** [comment]
image
the state drop down now shows undefined on allocations/calculations

**Comment by janetbutts** [comment]
@Chima1707 , @freefony , @tlvince , what needs to happen on this ticket?
cc: @nkhumphreys

**Comment by tlvince** [comment]
I believe most (if not all) of this is included in #355?

**Comment by freefony** [comment]
cool so we close #353

**Comment by tlvince** [comment]
@Chima1707?

**Comment by Chima1707** [comment]
Yeap, close #353,

**Comment by tlvince** [comment]
:+1:

**Pull request closed without merging**
