### PR TITLE
Add state-level access control

### PR DESCRIPTION
**Pull request by tlvince**
Adds state-level access control.

Usage:
- Run `gulp views fixtures users`
- Add a new role to the `gis` user, in the format:

```
direct_delivery_dashboard_state_[state_code]
```

... where `state_code` corresponds the lowercase `_id` of a state (level: 2) in
the `locations.json` fixtures. For example:

```
direct_delivery_dashboard_state_kn
```

In the planning tab, you should only see the Kano delivery round fixture listed (and not Bauchi).

### CODE REVIEW

**Comment by tlvince** [comment]
@jofomah here's the basic direction I'm heading with this.

**Comment by jofomah** [comment]
@tlvince lgtm, will confirm from Adamu Lawan if home page needs to be locked down too.

**Comment by jofomah** [comment]
@tlvince so the landing page should be accessible by any user that has access. but every other page should be locked by state or states the user is allowed to access or all if a super admin like Adamu Lawan.

**Comment by tlvince** [comment]
Boss.

**Comment by tlvince** [comment]
@jofomah @musamusa any idea what groups should be able to access the new Facility tab?

**Comment by tlvince** [comment]
Note, we don't have state-level support on most of the reports tab, so leaving access control out here for now.

Also not adding fine-grained access control to configurations tab as only super users are allowed to view it.

**Comment by tlvince** [comment]
@jofomah I think this is ready.

**Comment by jofomah** [comment]
@tlvince  cool will review tomorrow. Thanks

**Comment by jofomah** [comment]
@tlvince i don't see any thing on Delivery Rounds, when i login as a gis user, even though i assigned 'direct_delivery_dashboard_kn' to gis user roles. Am i missing something out.

**Comment by tlvince** [comment]
@jofomah which route are you browsing to? You may need to reset your local DB as I added a few new views (check you've not got anything in there that you need first):

```
 curl -X DELETE admin:admin@localhost:5984/deliveries && gulp -u admin -p admin fixtures views users
```

**Comment by tlvince** [comment]
@jofomah rebased.

**Comment by jofomah** [comment]
@tlvince  still cant see delivery rounds under planning if i login as gis user, but i do when i login as a super user

**Comment by tlvince** [comment]
OK, will check.

**Comment by tlvince** [comment]
This is what I see:

screen shot 2015-10-22 at 11 40 13

I added to rounds to the fixtures; KN-007-2015 and BA-008-2015.

**Pull request merged**
