### PR TITLE
Enhancement/renaming views

### PR DESCRIPTION
**Pull request by freefony**

### CODE REVIEW

**Comment by tlvince** [comment]
The consumers of these views will need updating, e.g. [assumptions#getAll](https://github.com/eHealthAfrica/direct-delivery-dashboard/blob/6cdceb9a239f299e4504e699fc27c45e6a5c9d1e/src/app/configurations/allocations/assumptions/assumptions.service.js#L13).

**Comment by freefony** [comment]
Based on what we have now, these views are not consumed but  all changes/updates to views between the coming release and the one after it should go into these views

**Comment by tlvince** [comment]
Oh, I see you've opted to make a copy of them (with the prefixed name). Any reason not to start using them now (and remove the others)?

**Comment by freefony** [comment]
From my understanding, we are only updating the app for kano users(drivers) right away and not for Bauchi users yet. so the Bauchi guys will keep calling the old views for now while kano should call the versioned  views

**Comment by tlvince** [comment]
Thanks!

**Pull request merged**
