### PR TITLE
Feauture/validate products form

### LINKED ISSUE #266: Add descriptive error message if product code already exist

### PR DESCRIPTION
**Pull request by Chima1707**
resolves #266

### CODE REVIEW

**Comment by janetbutts** [comment]
Please review @freefony

**Comment by janetbutts** [comment]
@freefony , please review asap

**Comment by freefony** [comment]
unique product directive should be separated into a instant validation feature branch and the product-by-code view is a duplicate of the existing products view

**Comment by janetbutts** [comment]
@Chima1707 , has this been addressed?

**Comment by Chima1707** [comment]
Yes,  i have done that

**Pull request merged**
