### PR TITLE
fix(invoice): use doc drop on unset facilityRounds

### LINKED ISSUE #275: Reporting: Invoice is not viewable
May be due to the fact that there was no driver data. If this is the case, raise an alert indicating that there is no data available from the round instead of just indicating a blank.

### PR DESCRIPTION
**Pull request by tlvince**
How to test this:
1. In planning tab, create new delivery round
2. Add facilities to the new round
3. In the schedule view, edit a delivery, fill in arbitrary details, choose
   status: "Success: 1st Attempt" and hit save
4. View the round in Reports > Invoice

The invoice table should be displayed.

Closes #275.

### CODE REVIEW

**Comment by tlvince** [comment]
Assigned to @janetbutts for reassigning based on availability.

**Comment by janetbutts** [comment]
@tlvince , i tested this and it worked. @musamusa , please review

**Comment by musamusa** [comment]
@tlvince kindly resolve conflict so I can merge
thanks

**Comment by tlvince** [comment]
@musamusa fixed.

**Pull request merged**
