### PR TITLE
Feature/delivery round report

### PR DESCRIPTION
**Pull request by hbj**
Some hints:
- The couch views and fixtures must be applied along with those from the mobile app
- To print the report with the background colours for the table cells, you must activate background printing in the browser

### CODE REVIEW

**Comment by hbj** [comment]
@tlvince @jofomah can you please review taking care of my comment above?

**Comment by hbj** [comment]
@tlvince, @jofomah, can anyone review please?

**Comment by tlvince** [comment]
@hbj, sorry, we got tied up. Looking at this now.

**Comment by tlvince** [comment]
lgtm. Lets see if we can swap in the jQuery dependency for something Angular at a later date.

**Pull request merged**
